INSERT INTO languages (3letter,2letter,englishname,frenchname) VALUES
('aar','aa','Afar','afar'),
('abk','ab','Abkhazian','abkhaze'),
('ace',NULL,'Achinese','aceh'),
('ach',NULL,'Acoli','acoli'),
('ada',NULL,'Adangme','adangme'),
('ady',NULL,'Adyghe; Adygei','adyghé'),
('afa',NULL,'Afro-Asiatic languages','afro-asiatiques, langues'),
('afh',NULL,'Afrihili','afrihili'),
('afr','af','Afrikaans','afrikaans'),
('ain',NULL,'Ainu','aïnou'),
('aka','ak','Akan','akan'),
('akk',NULL,'Akkadian','akkadien'),
('ale',NULL,'Aleut','aléoute'),
('alg',NULL,'Algonquian languages','algonquines, langues'),
('alt',NULL,'Southern Altai','altai du Sud'),
('amh','am','Amharic','amharique'),
('ang',NULL,'English, Old (ca.450-1100)','anglo-saxon (ca.450-1100)'),
('anp',NULL,'Angika','angika'),
('apa',NULL,'Apache languages','apaches, langues'),
('ara','ar','Arabic','arabe'),
('arc',NULL,'Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)','araméen d\'empire (700-300 BCE)'),
('arg','an','Aragonese','aragonais'),
('arm','hy','Armenian','arménien'),
('arn',NULL,'Mapudungun; Mapuche','mapudungun; mapuche; mapuce'),
('arp',NULL,'Arapaho','arapaho'),
('art',NULL,'Artificial languages','artificielles, langues'),
('arw',NULL,'Arawak','arawak'),
('asm','as','Assamese','assamais'),
('ast',NULL,'Asturian; Bable; Leonese; Asturleonese','asturien; bable; léonais; asturoléonais'),
('ath',NULL,'Athapascan languages','athapascanes, langues'),
('aus',NULL,'Australian languages','australiennes, langues'),
('ava','av','Avaric','avar'),
('ave','ae','Avestan','avestique'),
('awa',NULL,'Awadhi','awadhi'),
('aym','ay','Aymara','aymara'),
('aze','az','Azerbaijani','azéri'),
('bad',NULL,'Banda languages','banda, langues'),
('bai',NULL,'Bamileke languages','bamiléké, langues'),
('bak','ba','Bashkir','bachkir'),
('bal',NULL,'Baluchi','baloutchi'),
('bam','bm','Bambara','bambara'),
('ban',NULL,'Balinese','balinais'),
('baq','eu','Basque','basque'),
('bas',NULL,'Basa','basa'),
('bat',NULL,'Baltic languages','baltes, langues'),
('bej',NULL,'Beja; Bedawiyet','bedja'),
('bel','be','Belarusian','biélorusse'),
('bem',NULL,'Bemba','bemba'),
('ben','bn','Bengali','bengali'),
('ber',NULL,'Berber languages','berbères, langues'),
('bho',NULL,'Bhojpuri','bhojpuri'),
('bih','bh','Bihari','bihari'),
('bik',NULL,'Bikol','bikol'),
('bin',NULL,'Bini; Edo','bini; edo'),
('bis','bi','Bislama','bichlamar'),
('bla',NULL,'Siksika','blackfoot'),
('bnt',NULL,'Bantu languages','bantou, langues'),
('tib','bo','Tibetan','tibétain'),
('bos','bs','Bosnian','bosniaque'),
('bra',NULL,'Braj','braj'),
('bre','br','Breton','breton'),
('btk',NULL,'Batak languages','batak, langues'),
('bua',NULL,'Buriat','bouriate'),
('bug',NULL,'Buginese','bugi'),
('bul','bg','Bulgarian','bulgare'),
('byn',NULL,'Blin; Bilin','blin; bilen'),
('cad',NULL,'Caddo','caddo'),
('cai',NULL,'Central American Indian languages','amérindiennes de l\'Amérique centrale,  langues'),
('car',NULL,'Galibi Carib','karib; galibi; carib'),
('cat','ca','Catalan; Valencian','catalan; valencien'),
('cau',NULL,'Caucasian languages','caucasiennes, langues'),
('ceb',NULL,'Cebuano','cebuano'),
('cel',NULL,'Celtic languages','celtiques, langues; celtes, langues'),
('cha','ch','Chamorro','chamorro'),
('chb',NULL,'Chibcha','chibcha'),
('che','ce','Chechen','tchétchène'),
('chg',NULL,'Chagatai','djaghataï'),
('chi','zh','Chinese','chinois'),
('chk',NULL,'Chuukese','chuuk'),
('chm',NULL,'Mari','mari'),
('chn',NULL,'Chinook jargon','chinook, jargon'),
('cho',NULL,'Choctaw','choctaw'),
('chp',NULL,'Chipewyan; Dene Suline','chipewyan'),
('chr',NULL,'Cherokee','cherokee'),
('chu','cu','Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic','slavon d\'église; vieux slave; slavon liturgique; vieux bulgare'),
('chv','cv','Chuvash','tchouvache'),
('chy',NULL,'Cheyenne','cheyenne'),
('cmc',NULL,'Chamic languages','chames, langues'),
('cop',NULL,'Coptic','copte'),
('cor','kw','Cornish','cornique'),
('cos','co','Corsican','corse'),
('cpe',NULL,'Creoles and pidgins, English based','créoles et pidgins basés sur l\'anglais'),
('cpf',NULL,'Creoles and pidgins, French-based','créoles et pidgins basés sur le français'),
('cpp',NULL,'Creoles and pidgins, Portuguese-based','créoles et pidgins basés sur le portugais'),
('cre','cr','Cree','cree'),
('crh',NULL,'Crimean Tatar; Crimean Turkish','tatar de Crimé'),
('crp',NULL,'Creoles and pidgins','créoles et pidgins'),
('csb',NULL,'Kashubian','kachoube'),
('cus',NULL,'Cushitic languages','couchitiques,  langues'),
('wel','cy','Welsh','gallois'),
('cze','cs','Czech','tchèque'),
('dak',NULL,'Dakota','dakota'),
('dan','da','Danish','danois'),
('dar',NULL,'Dargwa','dargwa'),
('day',NULL,'Land Dayak languages','dayak, langues'),
('del',NULL,'Delaware','delaware'),
('den',NULL,'Slave (Athapascan)','esclave (athapascan)'),
('dgr',NULL,'Dogrib','dogrib'),
('din',NULL,'Dinka','dinka'),
('div','dv','Divehi; Dhivehi; Maldivian','maldivien'),
('doi',NULL,'Dogri','dogri'),
('dra',NULL,'Dravidian languages','dravidiennes,  langues'),
('dsb',NULL,'Lower Sorbian','bas-sorabe'),
('dua',NULL,'Duala','douala'),
('dum',NULL,'Dutch, Middle (ca.1050-1350)','néerlandais moyen (ca. 1050-1350)'),
('dyu',NULL,'Dyula','dioula'),
('dzo','dz','Dzongkha','dzongkha'),
('efi',NULL,'Efik','efik'),
('egy',NULL,'Egyptian (Ancient)','égyptien'),
('eka',NULL,'Ekajuk','ekajuk'),
('elx',NULL,'Elamite','élamite'),
('eng','en','English','anglais'),
('enm',NULL,'English, Middle (1100-1500)','anglais moyen (1100-1500)'),
('epo','eo','Esperanto','espéranto'),
('est','et','Estonian','estonien'),
('ewe','ee','Ewe','éwé'),
('ewo',NULL,'Ewondo','éwondo'),
('fan',NULL,'Fang','fang'),
('fao','fo','Faroese','féroïen'),
('fat',NULL,'Fanti','fanti'),
('fij','fj','Fijian','fidjien'),
('fil',NULL,'Filipino; Pilipino','filipino; pilipino'),
('fin','fi','Finnish','finnois'),
('fiu',NULL,'Finno-Ugrian languages','finno-ougriennes,  langues'),
('fon',NULL,'Fon','fon'),
('fre','fr','French','français'),
('frm',NULL,'French, Middle (ca.1400-1600)','français moyen (1400-1600)'),
('fro',NULL,'French, Old (842-ca.1400)','français ancien (842-ca.1400)'),
('frr',NULL,'Northern Frisian','frison septentrional'),
('frs',NULL,'Eastern Frisian','frison oriental'),
('fry','fy','Western Frisian','frison occidental'),
('ful','ff','Fulah','peul'),
('fur',NULL,'Friulian','frioulan'),
('gaa',NULL,'Ga','ga'),
('gay',NULL,'Gayo','gayo'),
('gba',NULL,'Gbaya','gbaya'),
('gem',NULL,'Germanic languages','germaniques, langues'),
('geo','ka','Georgian','géorgien'),
('ger','de','German','allemand'),
('gez',NULL,'Geez','guèze'),
('gil',NULL,'Gilbertese','kiribati'),
('gla','gd','Gaelic; Scottish Gaelic','gaélique; gaélique écossais'),
('gle','ga','Irish','irlandais'),
('glg','gl','Galician','galicien'),
('glv','gv','Manx','manx; mannois'),
('gmh',NULL,'German, Middle High (ca.1050-1500)','allemand, moyen haut (ca. 1050-1500)'),
('goh',NULL,'German, Old High (ca.750-1050)','allemand, vieux haut (ca. 750-1050)'),
('gon',NULL,'Gondi','gond'),
('gor',NULL,'Gorontalo','gorontalo'),
('got',NULL,'Gothic','gothique'),
('grb',NULL,'Grebo','grebo'),
('grc',NULL,'Greek, Ancient (to 1453)','grec ancien (jusqu\'�  1453)'),
('gre','el','Greek, Modern (1453-)','grec moderne (après 1453)'),
('grn','gn','Guarani','guarani'),
('gsw',NULL,'Swiss German; Alemannic; Alsatian','suisse alémanique; alémanique; alsacien'),
('guj','gu','Gujarati','goudjrati'),
('gwi',NULL,'Gwich\'in','gwich\'in'),
('hai',NULL,'Haida','haida'),
('hat','ht','Haitian; Haitian Creole','haïtien; créole haïtien'),
('hau','ha','Hausa','haoussa'),
('haw',NULL,'Hawaiian','hawaïen'),
('heb','he','Hebrew','hébreu'),
('her','hz','Herero','herero'),
('hil',NULL,'Hiligaynon','hiligaynon'),
('him',NULL,'Himachali','himachali'),
('hin','hi','Hindi','hindi'),
('hit',NULL,'Hittite','hittite'),
('hmn',NULL,'Hmong','hmong'),
('hmo','ho','Hiri Motu','hiri motu'),
('hrv','hr','Croatian','croate'),
('hsb',NULL,'Upper Sorbian','haut-sorabe'),
('hun','hu','Hungarian','hongrois'),
('hup',NULL,'Hupa','hupa'),
('iba',NULL,'Iban','iban'),
('ibo','ig','Igbo','igbo'),
('ice','is','Icelandic','islandais'),
('ido','io','Ido','ido'),
('iii','ii','Sichuan Yi; Nuosu','yi de Sichuan'),
('ijo',NULL,'Ijo languages','ijo, langues'),
('iku','iu','Inuktitut','inuktitut'),
('ile','ie','Interlingue; Occidental','interlingue'),
('ilo',NULL,'Iloko','ilocano'),
('ina','ia','Interlingua (International Auxiliary Language Association)','interlingua (langue auxiliaire internationale)'),
('inc',NULL,'Indic languages','indo-aryennes, langues'),
('ind','id','Indonesian','indonésien'),
('ine',NULL,'Indo-European languages','indo-européennes, langues'),
('inh',NULL,'Ingush','ingouche'),
('ipk','ik','Inupiaq','inupiaq'),
('ira',NULL,'Iranian languages','iraniennes, langues'),
('iro',NULL,'Iroquoian languages','iroquoises, langues'),
('ita','it','Italian','italien'),
('jav','jv','Javanese','javanais'),
('jbo',NULL,'Lojban','lojban'),
('jpn','ja','Japanese','japonais'),
('jpr',NULL,'Judeo-Persian','judéo-persan'),
('jrb',NULL,'Judeo-Arabic','judéo-arabe'),
('kaa',NULL,'Kara-Kalpak','karakalpak'),
('kab',NULL,'Kabyle','kabyle'),
('kac',NULL,'Kachin; Jingpho','kachin; jingpho'),
('kal','kl','Kalaallisut; Greenlandic','groenlandais'),
('kam',NULL,'Kamba','kamba'),
('kan','kn','Kannada','kannada'),
('kar',NULL,'Karen languages','karen, langues'),
('kas','ks','Kashmiri','kashmiri'),
('kau','kr','Kanuri','kanouri'),
('kaw',NULL,'Kawi','kawi'),
('kaz','kk','Kazakh','kazakh'),
('kbd',NULL,'Kabardian','kabardien'),
('kha',NULL,'Khasi','khasi'),
('khi',NULL,'Khoisan languages','khoïsan, langues'),
('khm','km','Central Khmer','khmer central'),
('kho',NULL,'Khotanese; Sakan','khotanais; sakan'),
('kik','ki','Kikuyu; Gikuyu','kikuyu'),
('kin','rw','Kinyarwanda','rwanda'),
('kir','ky','Kirghiz; Kyrgyz','kirghiz'),
('kmb',NULL,'Kimbundu','kimbundu'),
('kok',NULL,'Konkani','konkani'),
('kom','kv','Komi','kom'),
('kon','kg','Kongo','kongo'),
('kor','ko','Korean','coréen'),
('kos',NULL,'Kosraean','kosrae'),
('kpe',NULL,'Kpelle','kpellé'),
('krc',NULL,'Karachay-Balkar','karatchai balkar'),
('krl',NULL,'Karelian','carélien'),
('kro',NULL,'Kru languages','krou, langues'),
('kru',NULL,'Kurukh','kurukh'),
('kua','kj','Kuanyama; Kwanyama','kuanyama; kwanyama'),
('kum',NULL,'Kumyk','koumyk'),
('kur','ku','Kurdish','kurde'),
('kut',NULL,'Kutenai','kutenai'),
('lad',NULL,'Ladino','judéo-espagnol'),
('lah',NULL,'Lahnda','lahnda'),
('lam',NULL,'Lamba','lamba'),
('lao','lo','Lao','lao'),
('lat','la','Latin','latin'),
('lav','lv','Latvian','letton'),
('lez',NULL,'Lezghian','lezghien'),
('lim','li','Limburgan; Limburger; Limburgish','limbourgeois'),
('lin','ln','Lingala','lingala'),
('lit','lt','Lithuanian','lituanien'),
('lol',NULL,'Mongo','mongo'),
('loz',NULL,'Lozi','lozi'),
('ltz','lb','Luxembourgish; Letzeburgesch','luxembourgeois'),
('lua',NULL,'Luba-Lulua','luba-lulua'),
('lub','lu','Luba-Katanga','luba-katanga'),
('lug','lg','Ganda','ganda'),
('lui',NULL,'Luiseno','luiseno'),
('lun',NULL,'Lunda','lunda'),
('luo',NULL,'Luo (Kenya and Tanzania)','luo (Kenya et Tanzanie)'),
('lus',NULL,'Lushai','lushai'),
('mac','mk','Macedonian','macédonien'),
('mad',NULL,'Madurese','madourais'),
('mag',NULL,'Magahi','magahi'),
('mah','mh','Marshallese','marshall'),
('mai',NULL,'Maithili','maithili'),
('mak',NULL,'Makasar','makassar'),
('mal','ml','Malayalam','malayalam'),
('man',NULL,'Mandingo','mandingue'),
('mao','mi','Maori','maori'),
('map',NULL,'Austronesian languages','austronésiennes, langues'),
('mar','mr','Marathi','marathe'),
('mas',NULL,'Masai','massaï'),
('mdf',NULL,'Moksha','moksa'),
('mdr',NULL,'Mandar','mandar'),
('men',NULL,'Mende','mendé'),
('mga',NULL,'Irish, Middle (900-1200)','irlandais moyen (900-1200)'),
('mic',NULL,'Mi\'kmaq; Micmac','mi\'kmaq; micmac'),
('min',NULL,'Minangkabau','minangkabau'),
('mis',NULL,'Uncoded languages','langues non codées'),
('mkh',NULL,'Mon-Khmer languages','môn-khmer, langues'),
('mlg','mg','Malagasy','malgache'),
('mlt','mt','Maltese','maltais'),
('mnc',NULL,'Manchu','mandchou'),
('mni',NULL,'Manipuri','manipuri'),
('mno',NULL,'Manobo languages','manobo, langues'),
('moh',NULL,'Mohawk','mohawk'),
('mon','mn','Mongolian','mongol'),
('mos',NULL,'Mossi','moré'),
('may','ms','Malay','malais'),
('mul',NULL,'Multiple languages','multilingue'),
('mun',NULL,'Munda languages','mounda, langues'),
('mus',NULL,'Creek','muskogee'),
('mwl',NULL,'Mirandese','mirandais'),
('mwr',NULL,'Marwari','marvari'),
('bur','my','Burmese','birman'),
('myn',NULL,'Mayan languages','maya, langues'),
('myv',NULL,'Erzya','erza'),
('nah',NULL,'Nahuatl languages','nahuatl, langues'),
('nai',NULL,'North American Indian languages','nord-amérindiennes, langues'),
('nap',NULL,'Neapolitan','napolitain'),
('nau','na','Nauru','nauruan'),
('nav','nv','Navajo; Navaho','navaho'),
('nbl','nr','Ndebele, South; South Ndebele','ndébélé du Sud'),
('nde','nd','Ndebele, North; North Ndebele','ndébélé du Nord'),
('ndo','ng','Ndonga','ndonga'),
('nds',NULL,'Low German; Low Saxon; German, Low; Saxon, Low','bas allemand; bas saxon; allemand, bas; saxon, bas'),
('nep','ne','Nepali','népalais'),
('new',NULL,'Nepal Bhasa; Newari','nepal bhasa; newari'),
('nia',NULL,'Nias','nias'),
('nic',NULL,'Niger-Kordofanian languages','nigéro-kordofaniennes, langues'),
('niu',NULL,'Niuean','niué'),
('dut','nl','Dutch; Flemish','néerlandais; flamand'),
('nno','nn','Norwegian Nynorsk; Nynorsk, Norwegian','norvégien nynorsk; nynorsk, norvégien'),
('nob','nb','Bokmål, Norwegian; Norwegian Bokmål','norvégien bokmål'),
('nog',NULL,'Nogai','nogaï; nogay'),
('non',NULL,'Norse, Old','norrois, vieux'),
('nor','no','Norwegian','norvégien'),
('nqo',NULL,'N\'Ko','n\'ko'),
('nso',NULL,'Pedi; Sepedi; Northern Sotho','pedi; sepedi; sotho du Nord'),
('nub',NULL,'Nubian languages','nubiennes, langues'),
('nwc',NULL,'Classical Newari; Old Newari; Classical Nepal Bhasa','newari classique'),
('nya','ny','Chichewa; Chewa; Nyanja','chichewa; chewa; nyanja'),
('nym',NULL,'Nyamwezi','nyamwezi'),
('nyn',NULL,'Nyankole','nyankolé'),
('nyo',NULL,'Nyoro','nyoro'),
('nzi',NULL,'Nzima','nzema'),
('oci','oc','Occitan (post 1500)','occitan (après 1500)'),
('oji','oj','Ojibwa','ojibwa'),
('ori','or','Oriya','oriya'),
('orm','om','Oromo','galla'),
('osa',NULL,'Osage','osage'),
('oss','os','Ossetian; Ossetic','ossète'),
('ota',NULL,'Turkish, Ottoman (1500-1928)','turc ottoman (1500-1928)'),
('oto',NULL,'Otomian languages','otomi, langues'),
('paa',NULL,'Papuan languages','papoues, langues'),
('pag',NULL,'Pangasinan','pangasinan'),
('pal',NULL,'Pahlavi','pahlavi'),
('pam',NULL,'Pampanga; Kapampangan','pampangan'),
('pan','pa','Panjabi; Punjabi','pendjabi'),
('pap',NULL,'Papiamento','papiamento'),
('pau',NULL,'Palauan','palau'),
('peo',NULL,'Persian, Old (ca.600-400 B.C.)','perse, vieux (ca. 600-400 av. J.-C.)'),
('per','fa','Persian','persan'),
('phi',NULL,'Philippine languages','philippines, langues'),
('phn',NULL,'Phoenician','phénicien'),
('pli','pi','Pali','pali'),
('pol','pl','Polish','polonais'),
('pon',NULL,'Pohnpeian','pohnpei'),
('por','pt','Portuguese','portugais'),
('pra',NULL,'Prakrit languages','prâkrit, langues'),
('pro',NULL,'Provençal, Old (to 1500);Occitan, Old (to 1500)','provençal ancien (jusqu\'�  1500); occitan ancien (jusqu\'�  1500)'),
('pus','ps','Pushto; Pashto','pachto'),
('qaa-qtz',NULL,'Reserved for local use','réservée �  l\'usage local'),
('que','qu','Quechua','quechua'),
('raj',NULL,'Rajasthani','rajasthani'),
('rap',NULL,'Rapanui','rapanui'),
('rar',NULL,'Rarotongan; Cook Islands Maori','rarotonga; maori des îles Cook'),
('roa',NULL,'Romance languages','romanes, langues'),
('roh','rm','Romansh','romanche'),
('rom',NULL,'Romany','tsigane'),
('rum','ro','Romanian; Moldavian; Moldovan','roumain; moldave'),
('run','rn','Rundi','rundi'),
('rup',NULL,'Aromanian; Arumanian; Macedo-Romanian','aroumain; macédo-roumain'),
('rus','ru','Russian','russe'),
('sad',NULL,'Sandawe','sandawe'),
('sag','sg','Sango','sango'),
('sah',NULL,'Yakut','iakoute'),
('sai',NULL,'South American Indian languages','sud-amérindiennes, langues'),
('sal',NULL,'Salishan languages','salishennes, langues'),
('sam',NULL,'Samaritan Aramaic','samaritain'),
('san','sa','Sanskrit','sanskrit'),
('sas',NULL,'Sasak','sasak'),
('sat',NULL,'Santali','santal'),
('scn',NULL,'Sicilian','sicilien'),
('sco',NULL,'Scots','écossais'),
('sel',NULL,'Selkup','selkoupe'),
('sem',NULL,'Semitic languages','sémitiques, langues'),
('sga',NULL,'Irish, Old (to 900)','irlandais ancien (jusqu\'�  900)'),
('sgn',NULL,'Sign Languages','langues des signes'),
('shn',NULL,'Shan','chan'),
('sid',NULL,'Sidamo','sidamo'),
('sin','si','Sinhala; Sinhalese','singhalais'),
('sio',NULL,'Siouan languages','sioux, langues'),
('sit',NULL,'Sino-Tibetan languages','sino-tibétaines, langues'),
('sla',NULL,'Slavic languages','slaves, langues'),
('slo','sk','Slovak','slovaque'),
('slv','sl','Slovenian','slovène'),
('sma',NULL,'Southern Sami','sami du Sud'),
('sme','se','Northern Sami','sami du Nord'),
('smi',NULL,'Sami languages','sames, langues'),
('smj',NULL,'Lule Sami','sami de Lule'),
('smn',NULL,'Inari Sami','sami d\'Inari'),
('smo','sm','Samoan','samoan'),
('sms',NULL,'Skolt Sami','sami skolt'),
('sna','sn','Shona','shona'),
('snd','sd','Sindhi','sindhi'),
('snk',NULL,'Soninke','soninké'),
('sog',NULL,'Sogdian','sogdien'),
('som','so','Somali','somali'),
('son',NULL,'Songhai languages','songhai, langues'),
('sot','st','Sotho, Southern','sotho du Sud'),
('spa','es','Spanish; Castilian','espagnol; castillan'),
('alb','sq','Albanian','albanais'),
('srd','sc','Sardinian','sarde'),
('srn',NULL,'Sranan Tongo','sranan tongo'),
('srp','sr','Serbian','serbe'),
('srr',NULL,'Serer','sérère'),
('ssa',NULL,'Nilo-Saharan languages','nilo-sahariennes, langues'),
('ssw','ss','Swati','swati'),
('suk',NULL,'Sukuma','sukuma'),
('sun','su','Sundanese','soundanais'),
('sus',NULL,'Susu','soussou'),
('sux',NULL,'Sumerian','sumérien'),
('swa','sw','Swahili','swahili'),
('swe','sv','Swedish','suédois'),
('syc',NULL,'Classical Syriac','syriaque classique'),
('syr',NULL,'Syriac','syriaque'),
('tah','ty','Tahitian','tahitien'),
('tai',NULL,'Tai languages','tai, langues'),
('tam','ta','Tamil','tamoul'),
('tat','tt','Tatar','tatar'),
('tel','te','Telugu','télougou'),
('tem',NULL,'Timne','temne'),
('ter',NULL,'Tereno','tereno'),
('tet',NULL,'Tetum','tetum'),
('tgk','tg','Tajik','tadjik'),
('tgl','tl','Tagalog','tagalog'),
('tha','th','Thai','thaï'),
('tig',NULL,'Tigre','tigré'),
('tir','ti','Tigrinya','tigrigna'),
('tiv',NULL,'Tiv','tiv'),
('tkl',NULL,'Tokelau','tokelau'),
('tlh',NULL,'Klingon; tlhIngan-Hol','klingon'),
('tli',NULL,'Tlingit','tlingit'),
('tmh',NULL,'Tamashek','tamacheq'),
('tog',NULL,'Tonga (Nyasa)','tonga (Nyasa)'),
('ton','to','Tonga (Tonga Islands)','tongan (Îles Tonga)'),
('tpi',NULL,'Tok Pisin','tok pisin'),
('tsi',NULL,'Tsimshian','tsimshian'),
('tsn','tn','Tswana','tswana'),
('tso','ts','Tsonga','tsonga'),
('tuk','tk','Turkmen','turkmène'),
('tum',NULL,'Tumbuka','tumbuka'),
('tup',NULL,'Tupi languages','tupi, langues'),
('tur','tr','Turkish','turc'),
('tut',NULL,'Altaic languages','altaïques, langues'),
('tvl',NULL,'Tuvalu','tuvalu'),
('twi','tw','Twi','twi'),
('tyv',NULL,'Tuvinian','touva'),
('udm',NULL,'Udmurt','oudmourte'),
('uga',NULL,'Ugaritic','ougaritique'),
('uig','ug','Uighur; Uyghur','ouïgour'),
('ukr','uk','Ukrainian','ukrainien'),
('umb',NULL,'Umbundu','umbundu'),
('und',NULL,'Undetermined','indéterminée'),
('urd','ur','Urdu','ourdou'),
('uzb','uz','Uzbek','ouszbek'),
('vai',NULL,'Vai','vaï'),
('ven','ve','Venda','venda'),
('vie','vi','Vietnamese','vietnamien'),
('vol','vo','Volapük','volapük'),
('vot',NULL,'Votic','vote'),
('wak',NULL,'Wakashan languages','wakashanes, langues'),
('wal',NULL,'Wolaitta; Wolaytta','wolaitta; wolaytta'),
('war',NULL,'Waray','waray'),
('was',NULL,'Washo','washo'),
('wen',NULL,'Sorbian languages','sorabes, langues'),
('wln','wa','Walloon','wallon'),
('wol','wo','Wolof','wolof'),
('xal',NULL,'Kalmyk; Oirat','kalmouk; oïrat'),
('xho','xh','Xhosa','xhosa'),
('yao',NULL,'Yao','yao'),
('yap',NULL,'Yapese','yapois'),
('yid','yi','Yiddish','yiddish'),
('yor','yo','Yoruba','yoruba'),
('ypk',NULL,'Yupik languages','yupik, langues'),
('zap',NULL,'Zapotec','zapotèque'),
('zbl',NULL,'Blissymbols; Blissymbolics; Bliss','symboles Bliss; Bliss'),
('zen',NULL,'Zenaga','zenaga'),
('zha','za','Zhuang; Chuang','zhuang; chuang'),
('znd',NULL,'Zande languages','zandé, langues'),
('zul','zu','Zulu','zoulou'),
('zun',NULL,'Zuni','zuni'),
('zxx',NULL,'No linguistic content; Not applicable','pas de contenu linguistique; non applicable'),
('zza',NULL,'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki','zaza; dimili; dimli; kirdki; kirmanjki; zazaki');
