#!/bin/bash

NO_ARGS=0 
E_OPTERROR=85

error() {
  echo "error: $1"
  echo ""
  usage
}

usage() {
  echo "Usage:"
  echo "  `basename $0` -b branch [-n [-c] [-m]]"
  echo "    -b: The branch to ship. Creates a new tag."
  echo "    -n: Do not create a tag. Move production to specified branch only."
  echo "    -c: Apply cuts in -n mode."
  echo "    -m: Minify code in -n mode."
  echo "  `basename $0` -t tag"
  echo "    -t: Move or rollback production to the specified tag."
  echo "  `basename $0` -h"
  echo "    -h: Prints this help message."
  exit $E_OPTERROR
}

if [ $# -eq "$NO_ARGS" ]    # Script invoked with no command-line args?
then
  usage
fi

BRANCH=mainline
TAG=NOTAG
ROOTDIR=tags
PRODUCTIONHOST=chrome

# used for running a make command on the remote host for -c and -m options
MAKEFILECMD=echo

BRANCHSET=no
NMODE=no
APPLYCUTS=no
MINIFY=no
TAGSET=no

while getopts "hb:ncmt:" OPTION
do
  case $OPTION in
    b)
      BRANCH=$OPTARG
      if [ "$BRANCHSET" == "yes" ]
      then
        error "multiple branches specified, select only one"
      fi
      if [ "$TAGSET" == "yes" ]
      then
        error "can't specify a branch after specifying a tag"
      fi
      BRANCHSET=yes
      ;;
    n)
      NMODE=yes
      ;;
    c)
      APPLYCUTS=yes
      ;;
    m)
      MINIFY=yes
      ;;
    t)
      TAG=$OPTARG
      if [ "$BRANCHSET" == "yes" ]
      then
        error "can't specify a tag after specifying a branch"
      fi
      if [ "$TAGSET" == "yes" ]
      then
        error "multiple tags specified, select only one"
      fi
      TAGSET=yes
      ;;
    h)
      usage
      ;;
    ?)
      echo ""
      usage
      ;;
  esac
done

# error checking
if [ "$NMODE" == "no" ]
then
  if [ "$APPLYCUTS" == "yes" ]
  then
    error "can't specify -c without -n"
  fi
  if [ "$MINIFY" == "yes" ]
  then
    error "can't specify -m without -n"
  fi
fi
if [ "$NMODE" == "yes" ]
then
  if [ "$TAGSET" == "yes" ]
  then
    error "can't specify a tag in -n mode"
  fi
fi

pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd`
popd > /dev/null

pushd $SCRIPTPATH/..
svn up

pushd $SCRIPTPATH/../branches/$BRANCH
BUILDNUMBER=`make buildnumber`
if [ "$TAGSET" == "no" -a "$NMODE" == "no" ]
then
  NEWTAG=2.0-build-$BUILDNUMBER
else
  NEWTAG=$TAG
fi
if [ "$NMODE" == "yes" ]
then
  NEWTAG=$BRANCH
  ROOTDIR=branches
  MAKERULE=buildfinalize
  if [ "$APPLYCUTS" == "yes" ]
  then
    if [ "$MINIFY" == "yes" ]
    then
      MAKERULE=buildfinalize
    else
      MAKERULE=cutsfinalize
    fi
  else
    if [ "$MINIFY" == "yes" ]
    then
      MAKERULE=minifyfinalize
    else
      MAKERULE=signfinalize
    fi
  fi
  MAKEFILECMD="make $MAKERULE"
fi
popd

if [ "$TAGSET" == "no" -a "$NMODE" == "no" ]
then
  svn cp branches/$BRANCH tags/$NEWTAG
  pushd tags/$NEWTAG
  make buildfinalize
  svn ci -m "setsail production upgrade: 2.0 Build $BUILDNUMBER"
fi
popd

echo ""
echo "Please enter the production password."
ssh -tt root@$PRODUCTIONHOST <<END
pushd /var/www/localhost/htdocs/missionsconnector/
rm -rf *
svn export http://$PRODUCTIONHOST/svn/missionsconnector/$ROOTDIR/$NEWTAG --username system --force .
$MAKEFILECMD
rm -f Makefile
popd
exit
END

# vim: tw=0
